spring.application.name=myApp
# Base de données — Railway en production, locale en développement
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sysCoiffeur}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:salim1212}
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Port Railway
server.port=${PORT:8080}
# Cloudinary
cloudinary.cloud-name=dv2bjklhu
cloudinary.api-key=374539682937157
cloudinary.api-secret=qYjT8VHWmMwLfIQCQuvRbgmWl_g
# Stripea
stripe.api.key=${STRIPE_API_KEY:sk_test_51TLQuKDnhpF1jgjyuuuyuAIfb7eyOI2UxwxBQkKjap0j52o44hWXXaqShfGgl7EfVHwY4sKcj6xQw4SjJC0pCaVm00mlMlw69w}
stripe.public.key=pk_test_51TLQuKDnhpF1jgjywRaUqc1jdIzAtZFwGGpdoyC8BuMGN9KmuVjZxxWScp8KzDEHibVSBm1TkOStgYWPBLfWLmir00RxlLL94x
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:whsec_c3d245e75e434e835f6556d13f71214a5d69a758db7690ff5c0ad9e082ac6faa}
# JWT
jwt.secret=${JWT_SECRET:maCleSecreteSuperLongueEtSecretePourSignerLesTokensJWTDuProjetCoiffeur2026}
jwt.expiration=86400000
# Google OAuth2
google.client.id=${GOOGLE_CLIENT_ID:681462135328-olls77t7uuqtjablr8sfoki1jn5v689g.apps.googleusercontent.com}
# Compte ROOT
root.email=lamgharisalim7@gmail.com